### ISSUE TITLE
Question about strange includes

### ISSUE THREAD

**Issue by Rillke** [kyro46/assPaintQuestion#27]
Hi,

[class.assPaintQuestionExport.php](https://github.com/kyro46/assPaintQuestion/blob/master/classes/export/qti12/class.assPaintQuestionExport.php#L85) (and others) `include_once` themselves. What's the purpose of this?

**Comment by kyro46** [comment]
In the named file are two includes. One for the ilXmlWriter to create the output and one for assQuestionExport for inheritance. I can't see what you mean, please name a line.

**Comment by Rillke** [comment]
I meant the first include but you are right, it's the inherited class. Btw, why is it included and not `required`?

https://github.com/kyro46/assPaintQuestion/blob/af09105db559eaf02f110516f73593f08c8ccd98/classes/export/qti12/class.assPaintQuestionExport.php#L3
