### ISSUE TITLE
Transparency replaced with black in user results view

### ISSUE THREAD

**Issue by Rillke** [kyro46/assPaintQuestion#28]
When viewing the user results, the plugin creates an image from the background blending the user solution on top using `imagecopyresampled()`. However, during this process, the background's transparency is replaced with solid black color.

When the student used black color on a transparent area to answer the question, the examiner can't distinguish the black user solution from the black background.

Relevant documentation:

> Transparency is copied only with [imagecopymerge()](https://www.php.net/manual/en/function.imagecopymerge.php) and true color images, not with [imagecopy()](https://www.php.net/manual/en/function.imagecopy.php) or pallete images.

* https://www.php.net/manual/en/function.imagecolortransparent.php#89927
* https://stackoverflow.com/q/2611852/2683737

**Comment by kyro46** [comment]
Confirmed. Will have a look at possible solutions.

**Comment by kyro46** [comment]
Converting transparency to white seemed like a reasonable solution. Please test.

**Comment by Rillke** [comment]
The editor should have the same background color as used when blending the background image and solution on it in test results view. Can you then also ensure a white background for the editor, please?

**Comment by Rillke** [comment]
s/The editor/The drawing canvas/

**Comment by kyro46** [comment]
Will have a look at this. I'm tending to convert all (newly) uploaded images to a single format (jpg) so performance draining handling afterwards becomes obsolete.

**Comment by frauklee** [comment]
The same behaviour (the background's transparency is replaced with solid black color) still occurs when you use a userdefined-sized backgroundimage.

steps zu reproduce:
1. create a Paint-Question
2. edit properties, fill them out an use  a background image with Canvas size = "use own size"
