### ISSUE TITLE
Sometimes black Image instead of painted canvas in ILIAS 5.x

### ISSUE THREAD

**Issue by kyro46** [kyro46/assPaintQuestion#9]
fix css

**Comment by kyro46** [comment]
Seems to be a problem with *.gif.

**Comment by Rillke** [comment]
Hi, is there a commit that resolved that issue? I see a restriction was introduced that limited the file types to png and jpeg.

**Comment by kyro46** [comment]
I assume when checking my memory aid aka issues, it had become obsolete after changing libs. As you can see, there is some code left for handling gif, but I decided not to support this format anymore because AFAIK nobody used it anyway. Nobody complained since.
